# Generated by Django 2.2 on 2020-04-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='Search',
            new_name='search',
        ),
    ]
